name: CI/CD Docker + Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Login a Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3) Build de imagen apuntando a la carpeta CORRECTA
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/holamundoapp:latest ./WebApplication1

      # 4) Push a Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/holamundoapp:latest

      # 5) Disparar deploy en Render usando el DEPLOY HOOK
      - name: Trigger Render deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
